# Generated by Django 4.0.2 on 2022-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "tag",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
            ],
        ),
    ]
