# Generated by Django 4.0.2 on 2022-06-25 07:02

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farms", "0004_farm_farm_group_iotbox_ssh_port_issuetracker_photos"),
        ("pdc", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlantFlowering",
            new_name="ReproductiveGrowth",
        ),
        migrations.AlterModelOptions(
            name="reproductivegrowth",
            options={
                "verbose_name": "Reproductive Growth",
                "verbose_name_plural": "Reproductive Growth",
            },
        ),
        migrations.RemoveField(
            model_name="plantanalysis",
            name="image",
        ),
        migrations.AddField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="decommission_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_decommission_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="decommission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="harvesting",
            name="brix_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="harvesting",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="harvesting",
            name="stage",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="photos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="nurseryhealth",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plantanalysis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantanalysis",
            name="photos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="plantanalysis",
            name="specimen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pdc.specimen",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="specimen",
            name="decommission_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimen_decommission_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="decommission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specimen",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vegetativegrowth",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vegetativegrowth",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vegetativegrowth",
            name="stem_diameter_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coolingpad",
            name="remarks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), size=None
            ),
        ),
        migrations.AlterField(
            model_name="domeparameters",
            name="par_meter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outsideparameters",
            name="weather",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vegetativegrowth",
            name="fruit_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vegetativegrowth",
            name="leaves_in_petioles",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vegetativegrowth",
            name="length_of_petioles",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vegetativegrowth",
            name="no_of_branches",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vegetativegrowth",
            name="no_of_petioles",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
