# Generated by Django 4.0.4 on 2022-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0004_remove_batch_datetime_remove_controller_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesting',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
