# Generated by Django 4.0.4 on 2022-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0005_harvesting_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvesting',
            name='stage',
        ),
        migrations.AddField(
            model_name='specimenoutput',
            name='stage_of_harvest',
            field=models.CharField(default='', max_length=50),
        ),
    ]
