# Generated by Django 4.0.4 on 2022-10-28 05:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_remove_farmmanagerattendance_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdc', '0007_rename_media_filter_outerwatertank_media_filter_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafAreaDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('leaf_number', models.IntegerField()),
                ('image_url_b', models.CharField(max_length=128)),
                ('image_url_g', models.CharField(max_length=128)),
                ('bg_area', models.IntegerField()),
                ('leaf_area', models.IntegerField()),
                ('script_version', models.CharField(max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.farm')),
                ('specimen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pdc.specimen')),
            ],
            options={
                'verbose_name': 'LeafAreaDetection',
                'verbose_name_plural': 'LeafAreaDetection',
            },
        ),
    ]
