# Generated by Django 4.1.3 on 2022-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0008_leafareadetection"),
    ]

    operations = [
        migrations.AddField(
            model_name="reproductivegrowth",
            name="remarks",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vegetativegrowth",
            name="remarks",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
