# Generated by Django 3.2.15 on 2022-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0008_leafareadetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafareadetection',
            name='bg_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leafareadetection',
            name='leaf_area',
            field=models.FloatField(),
        ),
    ]
