# Generated by Django 3.2.15 on 2022-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0009_auto_20221028_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafareadetection',
            name='image_url',
            field=models.CharField(default='.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leafareadetection',
            name='template_size',
            field=models.IntegerField(default=8250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domeparameters',
            name='lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outsideparameters',
            name='lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rootzonetemperature',
            name='surface_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
