# Generated by Django 3.2.15 on 2022-11-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0009_reproductivegrowth_remarks_vegetativegrowth_remarks'),
        ('pdc', '0010_auto_20221104_1513'),
    ]

    operations = [
    ]
