# Generated by Django 4.1.3 on 2022-11-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0011_merge_20221123_2334"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harvesting",
            name="section",
        ),
        migrations.AddField(
            model_name="harvesting",
            name="average_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="harvesting",
            name="variety",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="final_ec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="final_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="final_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="new_ec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="new_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="innerwatertank",
            name="new_water_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="input_ec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="input_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="waste_ec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="waste_lph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="waste_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outerwatertank",
            name="waste_pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vegetativegrowth",
            name="stem",
            field=models.IntegerField(
                blank=True, choices=[(1, "A"), (2, "B")], null=True
            ),
        ),
    ]
