# Generated by Django 4.0.2 on 2022-05-30 12:17

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "mobile",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999),
                            django.core.validators.MinValueValidator(1000000000),
                        ],
                    ),
                ),
                ("photo", models.URLField(blank=True, null=True)),
                (
                    "kyc_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Aadhar Card"),
                            (1, "PAN Card"),
                            (2, "Voter Card"),
                            (3, "Family Card"),
                        ],
                        null=True,
                    ),
                ),
                ("kyc_number", models.BigIntegerField(blank=True, null=True)),
                ("kyc_front", models.URLField(blank=True, null=True)),
                ("kyc_back", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False, editable=False)),
                ("user_id", models.IntegerField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("farms", models.ManyToManyField(to="farms.Farm")),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField(default=0)),
                ("description", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("work_quuantity", models.IntegerField(default=0)),
                ("recipe", models.JSONField()),
                ("recipe_quantity", models.IntegerField(default=0)),
                ("water_quantity", models.IntegerField(default=0)),
                ("dome", models.IntegerField(default=0)),
                (
                    "remarks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="farms.farm"
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="labour.labour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Work",
                "verbose_name_plural": "Labour Work",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "action",
                    models.IntegerField(
                        choices=[(0, "PUNCH IN"), (1, "PUNCH OUT"), (2, "ABSENT")]
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labour_farm",
                        to="farms.farm",
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="labour.labour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
            },
        ),
    ]
