# Generated by Django 4.0.4 on 2022-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_alter_work_recipe_quantity_alter_work_water_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_quuantity',
            new_name='work_quantity',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='work',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='work',
            name='recipe',
            field=models.JSONField(null=True),
        ),
    ]
