# Generated by Django 4.0.2 on 2022-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farm_farm_group_iotbox_ssh_port_issuetracker_photos"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="farms",
            field=models.ManyToManyField(blank=True, null=True, to="farms.Farm"),
        ),
    ]
