# Generated by Django 4.0.2 on 2022-05-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuetracker",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="issuetracker",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="iotbox",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="iotboxes",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="farmmanagerattendance",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farms.farm"
            ),
        ),
        migrations.AddField(
            model_name="farmmanagerattendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="iotbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="iotbox",
                to="farms.iotbox",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farms.farm"
            ),
        ),
    ]
