# Generated by Django 4.0.2 on 2022-06-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuetracker",
            name="photo",
        ),
    ]
