# Generated by Django 4.0.2 on 2022-06-25 07:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_remove_issuetracker_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="farm_group",
            field=models.CharField(default="farm", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iotbox",
            name="ssh_port",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issuetracker",
            name="photos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
    ]
