# Generated by Django 4.0.4 on 2022-08-23 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0004_farm_farm_group_iotbox_ssh_port_issuetracker_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmmanagerattendance',
            name='datetime',
        ),
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iotbox',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iotbox',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='actions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuetracker_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='component',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='issue',
            field=models.CharField(max_length=200),
        ),
    ]
